### ISSUE TITLE
OpenAPI 3.1 and JSON Schema Draft 2019-09 Support

### ISSUE THREAD

**Issue by jchook** [openapi-contrib/openapi-schema-to-json-schema#13]
Any plans to support the [very welcome upcoming changes](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md) to OpenAPI?

**Comment by philsturgeon** [comment]
We wont need to, OpenAPI and JSON Schema will be the same thing, so there's no need to convert anything. 🥳

**Comment by jchook** [comment]
Ok! I read this

> Schema Object
> The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is a superset of the JSON Schema Specification Draft 2019-09.

and thought that meant they may have added more validation atop JSON Schema.

Thanks
