### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'properties'

### ISSUE THREAD

**Issue by eobeda** [openapi-contrib/openapi-schema-to-json-schema#63]
[schema.json.txt](https://github.com/openapi-contrib/openapi-schema-to-json-schema/files/11192475/schema.json.txt)

Node.js v18.15.0
@openapi-contrib/openapi-schema-to-json-schema  version: 4.0.4

Hi,
I am trying to use an OpenApi 3.0.x document produced via Swashbuckle.AspNetCore version=6.5.0 as the input.  CJS format for nodejs.  Sample script to below.

I narrowed down the OpenApi document to just the schema section and have attached it. Both the full OpenApi document and schema section provide the same _"TypeError: Cannot use 'in' operator to search for 'properties'"_ error.  Trace is listed below.

dist\cjs\lib\converters\schema.js:58:22
``` javascript
if ("properties" in convertedSchema) {
```
Unfortunately just converting it to 'includes', an mdn recommendation, just causes a cascading of errors.
``` javascript
if ( convertedSchema.includes("properties")) {
```

Any suggestions on how to resolve the issue? Did I misunderstand the purpose of the tool? 
Thanks for looking into this.
Ed

**Sample test script:** execute it with the path to the schema file as a command line argument.

``` javascript
//var toJsonSchema = require('@openapi-contrib/openapi-schema-to-json-schema');
var { openapiSchemaToJsonSchema: toJsonSchema } = require("@openapi-contrib/openapi-schema-to-json-schema");

// Make sure we got a filename on the command line.
if (process.argv.length < 3) {
    console.log('Usage: node ' + process.argv[1] + ' FILENAME');
    process.exit(1);
}
// Read the file and print its contents.
var fs = require('fs')
    , filename = process.argv[2];

fs.readFile(filename, 'utf8', function (err, data) {
    if (err) throw err;

    var convertedSchema = toJsonSchema(data);

    console.log(convertedSchema);

});
```

**Trace Message:**

 at convertSchema (D:\Source\VSProjects\SubmitSite\node_modules\@openapi-contrib\openapi-schema-to-json-schema\dist\cjs\lib\converters\schema.js:58:22)
    at convertFromSchema (D:\Source\VSProjects\SubmitSite\node_modules\@openapi-contrib\openapi-schema-to-json-schema\dist\cjs\lib\converters\schema.js:12:23)
    at openapiSchemaToJsonSchema (D:\Source\VSProjects\SubmitSite\node_modules\@openapi-contrib\openapi-schema-to-json-schema\dist\cjs\index.js:54:37)
    at D:\Source\VSProjects\SubmitSite\SubmitSite\nodeScripts\OpenApiToSchema.js:18:27
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

**Comment by jonluca** [comment]
It looks like you're passing in a string to `toJsonSchema` - this expects an object, not a string. If the file you're reading is a json file, do:

```js
//var toJsonSchema = require('@openapi-contrib/openapi-schema-to-json-schema');
var { openapiSchemaToJsonSchema: toJsonSchema } = require("@openapi-contrib/openapi-schema-to-json-schema");

// Make sure we got a filename on the command line.
if (process.argv.length < 3) {
    console.log('Usage: node ' + process.argv[1] + ' FILENAME');
    process.exit(1);
}
// Read the file and print its contents.
var fs = require('fs')
    , filename = process.argv[2];

fs.readFile(filename, 'utf8', function (err, data) {
    if (err) throw err;

    var convertedSchema = toJsonSchema(JSON.parse(data));

    console.log(convertedSchema);

});
```

If it's a YAML file, you'll need to convert it to json before calling `toJsonSchema`, using something like https://www.npmjs.com/package/swagger-cli

**Comment by eobeda** [comment]
Perfect, thanks for the excellent help. That was the issue.
Keep up the good work.
