### ISSUE TITLE
Objects are cloned with prototypes

### ISSUE THREAD

**Issue by bryfox** [openapi-contrib/openapi-schema-to-json-schema#64]
In version 4, cloned objects are created with the prototype of another object:

https://github.com/openapi-contrib/openapi-schema-to-json-schema/blob/8c923eee390935fe530a55596c2151294e55b6f1/src/lib/utils/cloneDeep.ts#L20

The practical implication for me is that I'm passing my converted schemas to https://github.com/bcherny/json-schema-to-typescript/, which internally checks that object inputs are "plain objects" (according to lodash: https://docs-lodash.com/v4/is-plain-object/). The result is that my generated types are empty when using v4 of this library, but are OK when using v3.

Would it be possible to create these objects with a null prototype, or as literals?

**Comment by jonluca** [comment]
Sounds reasonable to me - all that needs to be changed is for `Object.create({}); ` to become `{}`, right?
