### ISSUE TITLE
feat: support deeply nested `definitionKeywords`

### ISSUE THREAD

**Issue by toomuchdesign** [openapi-contrib/openapi-schema-to-json-schema#67]
First of all, a big thank you for maintaining this library!

As far as I can see, `definitionKeywords` supports [one single nesting level](https://github.com/openapi-contrib/openapi-schema-to-json-schema/blob/abd2e4ac786c79c8db9b3ec4462be4eaaa6a4380/src/lib/converters/schema.ts#L65).

```js
var schema = {
  definitions: {
    sharedDefinition: ...
  },
};
```
..but I happened to see shared definitions nested 1+ levels down:

```js
var schema = {
  components: {
    schemas: {
       sharedDefinition: ...
    }
  },
};
```
Is it a use case this library could add support for?

In order to implement it in a non-breaking change we could extend `definitionKeywords` to:
- optionally accept an array of array of strings representing the definition paths: `[["components"], ["schema"]]`
- introduce a library to support dot notation: `components.schemas`
- any other solution?

I'm pinging to share with you this use case and to offer my availability to put together a PR with the solution you consider more appropriate.

Cheers!

**Comment by jonluca** [comment]
I like the dot notation idea - it should be really straightforward to use lodash's `.get` for this https://github.com/lodash/lodash/issues/1637

I wonder if theres any definitions that include periods that we'd need to be backwards compatible with?

Maybe as long as we check if the nested exists first, and if it doesn't, then fallback to pure name matching, that should work

**Comment by toomuchdesign** [comment]
I checked lodash's `get` and found that it works the opposite way than you mentioned, matching the pure name first (even if containing dots) and the nested then.

BTW it seems the behaviour we need in order to be non-breaking. Am I missing anything?

If good enough happy to open a PR.

**Comment by jonluca** [comment]
Oh great, yeah I think that's what we need to prevent breaking behavior. Yes that sounds good, I think it should be straightforward to add

**Comment by jonluca** [comment]
Ok added an initial version here, I think this solves your use case https://github.com/openapi-contrib/openapi-schema-to-json-schema/pull/69

**Comment by toomuchdesign** [comment]
Wow! Thank you @jonluca
