### ISSUE TITLE
how can i use this to mass-convert an entire oas yaml file to a json file?

### ISSUE THREAD

**Issue by daniellizik** [openapi-contrib/openapi-schema-to-json-schema#75]
do i really need to traverse through my entire yml spec and convert each schema?

**Comment by vickkhera** [comment]
I'm trying to do the same. My first step was to convert it all to a JSON OAS3 file:

```sh
npx @redocly/cli bundle -o /tmp/x.json  __design__/jsonobjects.yml
```

However, when I try to convert the OAS3 spec to json schema it does basically nothing:

```sh
npx @openapi-contrib/openapi-schema-to-json-schema --input /tmp/x.json --output /tmp/out.json
```

The output file difference from the input file:

```diff
4712c4712,4713
<   }
---
>   },
>   "$schema": "http://json-schema.org/draft-04/schema#"
```

The documentation is quite confusing in this regard. The CLI usage example kind of implies it will do this but apparently not.

There is a link to a CLI to convert the whole schema but that repo says it is no longer maintained, and it only does API requests, not all components. I have been using yaml-to-json-schema but it requires some manual fixes in the generated schema and deals poorly with external references.

**Comment by daniellizik** [comment]
sorry i'm dumb, gotta use swagger parser `dereference` api for this. not part of this repo

**Comment by wangyoucao577** [comment]
> I'm trying to do the same. My first step was to convert it all to a JSON OAS3 file:
> 
> ```shell
> npx @redocly/cli bundle -o /tmp/x.json  __design__/jsonobjects.yml
> ```
> 
> However, when I try to convert the OAS3 spec to json schema it does basically nothing:
> 
> ```shell
> npx @openapi-contrib/openapi-schema-to-json-schema --input /tmp/x.json --output /tmp/out.json
> ```
> 
> The output file difference from the input file:
> 
> ```diff
> 4712c4712,4713
> <   }
> ---
> >   },
> >   "$schema": "http://json-schema.org/draft-04/schema#"
> ```
> 
> The documentation is quite confusing in this regard. The CLI usage example kind of implies it will do this but apparently not.
> 
> There is a link to a CLI to convert the whole schema but that repo says it is no longer maintained, and it only does API requests, not all components. I have been using yaml-to-json-schema but it requires some manual fixes in the generated schema and deals poorly with external references.

+1
