### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by yannh** [openapi-contrib/openapi-schema-to-json-schema#8]
A few months ago, a note was added to the Readme indicating that this package is now "Treeware".

While of course you can license your software under any license, the original software at https://github.com/mikunn/openapi-schema-to-json-schema did not mention any such requirement - (nor did it provide any license... always add a License to your code I guess).

While I'm all for planting :evergreen_tree:  trees :deciduous_tree: , this means embedding this as a library into any software passes the "cost" on to potential users. Would releasing using a well-known license such as MIT/BSD/Apache be a possibility - with eventually a note asking to plant a tree?

Thanks!

**Comment by philsturgeon** [comment]
Treeware is not a software license. 

The license is MIT. 🙌🏻

https://github.com/openapi-contrib/openapi-schema-to-json-schema/blob/master/package.json
